flj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from bomber.api_views import BomberViewSet
from places.api_views import PlaceViewSet
from labels.api_views import LabelViewSet
from crew.api_views import PersonViewSet

from autocomplete_light import shortcuts as al
al.autodiscover()


router = routers.DefaultRouter()
router.register(r'bombers', BomberViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'labels', LabelViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'labels/', include('labels.urls', namespace='labels')),
    url(r'bombers/', include('bomber.urls', namespace='bombers')),
    url(r'browsing/', include('browsing.urls', namespace='browsing')),
    url(r'crew/', include('crew.urls', namespace='crew')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
]

labels/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^list/$', views.LabelListView.as_view(), name='label_list'),
url(r'^create/$', views.label_create, name='label_create'),
url(r'^edit/(?P<pk>[0-9]+)$', views.label_edit, name='label_edit'),
url(r'^delete/(?P<pk>[0-9]+)$', views.LabelDelete.as_view(), name='label_delete'),
]

labels/models.py
from django.db import models


class Label(models.Model):
    label = models.CharField(max_length=100, blank=True, help_text="The entities label or name.")
    label_type = models.CharField(max_length=255, blank=True, help_text="The type of the label.")
    isoCode = models.CharField(
        max_length=3, blank=True, help_text="The ISO 639-3 code for the label's language."
    )

    def __str__(self):
        return "{}".format(self.label)

labels/forms.py
from django import forms
from autocomplete_light import shortcuts as al
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div

from .autocomplete_light_registry import LabelAutocomplete, LabelTypeAutocomplete
from .models import Label


class LabelForm(al.ModelForm):
	isoCode = forms.CharField(required=True,
		widget=al.TextWidget('LabelAutocomplete'),
		label = "ISO 639-3")
	label_type = forms.CharField(required=False,
		widget = al.TextWidget('LabelTypeAutocomplete'),
		label = "Type of the Label") 
	label = forms.CharField(required=True,help_text="The entities label or name.")

	class Meta:
		model = Label
		fields = [ 'label','label_type', 'isoCode']

	def __init__(self, *args, **kwargs):
		super(LabelForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_tag = True
		self.helper.add_input(Submit('submit','Speichern'))

labels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic.edit import DeleteView
from django.views import generic

from .models import Label
from .forms import LabelForm


class LabelListView(generic.ListView):
	model = Label
	template_name = 'labels/labels_list.html'
	context_object_name = 'object_list'

	def get_queryset(self):
		return Label.objects.order_by('label')


def label_create(request):
	if request.method == "POST":
		form = LabelForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('labels:label_list')
		else:
			return render (request, 'labels/label_create.html', {'form':form})
	else:
		form = LabelForm()
		return render (request, 'labels/label_create.html', {'form':form})


def label_edit(request, pk):
	instance = get_object_or_404(Label, pk=pk)
	if request.method == "POST":
		form = LabelForm(request.POST, instance=instance)
		if form.is_valid():
			form.save()
			return redirect('labels:label_list')
		else:
			return render (request, 'labels/label_create.html', {'form':form,'instance':instance})
	else:
		form = LabelForm(instance=instance)
		return render(request, 'labels/label_create.html', {'form':form, 'instance':instance})


class LabelDelete(DeleteView):
	model = Label
	template_name = 'webpage/confirm_delete.html'
	success_url = reverse_lazy('labels:label_list')

labels/templates/labels/label_al.html
{% load autocomplete_light_tags %}

<div class="autocomplete-label">
{% for choice in choices %}
<span class="block autocomp_span" replace-text="{{ choice.ref_name }}" data-value="{{ choice.isoID }}">

    <b>{{ choice.ref_name }}</b>|{{choice.isoID}}

    
</span>

{% endfor %}
</div>

labels/templates/labels/label_create.html
{% extends "webpage/base.html" %}

{% block Titel %}Create Label{% endblock %}
{% block scriptHeader %}
{% include 'autocomplete_light/static.html' %}
{% endblock %}
{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
    	<h3>Create</h3>
    </div>
    <div class="panel-body">
    	{% load crispy_forms_tags %}
    	{% csrf_token %}
    	{% crispy form %}
        {% if instance %}
            <a class ="btn btn-danger btn-sm" href="{% url 'labels:label_delete' pk=instance.id %}">delete</a>
        {% endif %}
    </div>
</div>
<script>
    // Script to parse the autocomplete input and to subsitute the entered string (fetched via autocomplete) through this part of the fetched string, which should be stored in the db. 
    $( "#submit-id-submit" ).click(function() {
        var dataToChange = $( "#id_isoCode").val().split("|");
        console.log(dataToChange.length);
        console.log(dataToChange);
        if(dataToChange.length === 2){
            console.log("dataToChange");
            $( "#id_isoCode").val(dataToChange[1]);
        }             
});
</script>

{% endblock %}

labels/templates/labels/labels_list.html
{% extends "webpage/base.html" %}
{% block Titel %} See all Labels {% endblock %}
{% block content %}

<div class="panel panel-default">
	<div class="panel-heading">
		<h1>All Labels</h1>
		<div>
			<a class="btn btn-primary btn-lg" href="{% url 'labels:label_create' %}">create new Label</a>
		</div>
	</div>
	<div class="panel-body">
		{% if object_list %}
		<table class="table table-striped">
			<thead>
				<th>Label</th>
				<th>Label Type</th>
				<th>ISO 639-3</th>
			</thead>
			<tbody>
			{% for object in object_list %}
				<tr>
					<td>{{ object }}<br/><a href="{% url 'labels:label_edit' pk=object.id %}">{{ object.label }}</a></td>
					<td>{{ object.label_type }}</td>
					<td>{{ object.isoCode }}</a></td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		{% endif %}
	</div>
</div>
{% endblock %}

labels/templates/labels/labeltype_al.html
{% load autocomplete_light_tags %}

<div class="autocomplete-label">
{% for choice in choices %}
<span class="block autocomp_span" replace-text="{{ choice }}" data-value="{{ choice.name }}">

    <b>{{ choice.name }}</b> {{ choice.description }}

    
</span>

{% endfor %}
</div>