flj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from bomber.api_views import BomberViewSet
from places.api_views import PlaceViewSet
from labels.api_views import LabelViewSet
from crew.api_views import PersonViewSet

from autocomplete_light import shortcuts as al
al.autodiscover()


router = routers.DefaultRouter()
router.register(r'bombers', BomberViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'labels', LabelViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'labels/', include('labels.urls', namespace='labels')),
    url(r'bombers/', include('bomber.urls', namespace='bombers')),
    url(r'browsing/', include('browsing.urls', namespace='browsing')),
    url(r'crew/', include('crew.urls', namespace='crew')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
]

labels/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^list/$', views.LabelListView.as_view(), name='label_list'),
url(r'^create/$', views.label_create, name='label_create'),
url(r'^edit/(?P<pk>[0-9]+)$', views.label_edit, name='label_edit'),
url(r'^delete/(?P<pk>[0-9]+)$', views.LabelDelete.as_view(), name='label_delete'),
]

places/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^list/$', views.PlaceListView.as_view(), name='place_list'),
url(r'^create/$', views.create_place, name='place_create'),
url(r'^edit/(?P<pk>[0-9]+)$', views.edit_place, name='place_edit'),
url(r'^delete/(?P<pk>[0-9]+)$', views.PlaceDelete.as_view(), name='place_delete')
]

places/models.py
from django.db import models
from labels.models import Label


class Place(models.Model):

    """Holds information about places."""
    name = models.CharField(
        max_length=250, blank=True,
        help_text="Normalisierte, gegenwärtige Ortsbezeichnung")
    alternative_name = models.ManyToManyField(
        Label,
        max_length=250, blank=True,
        help_text="Alternative names")
    geonames_id = models.CharField(
        max_length=50, blank=True, help_text="GND-ID")
    lat = models.DecimalField(
        max_digits=20, decimal_places=12, blank=True, null=True)
    lng = models.DecimalField(
        max_digits=20, decimal_places=12, blank=True, null=True)

    def __str__(self):
        if self.alternative_name.exists():
            return self.name +" (" + " ".join([str(x.label) for x in self.alternative_name.all()]) + ")"
        else:
            return self.name

places/forms.py
# -*- coding: utf-8 -*-
from autocomplete_light import shortcuts as al
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import ModelForm

from .autocomplete_light_registry import NameAutocomplete
from labels.models import Label
from .models import Place

class PlaceForm(al.ModelForm):
	class Meta:
		model = Place
		fields = ['name', 'alternative_name', 'geonames_id', 'lat', 'lng']

	def __init__(self, *args, **kwargs):
		super(PlaceForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_tag = False

places/views.py
import requests, re, json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import (render, render_to_response, get_object_or_404,
	redirect)
from django.views import generic
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse, reverse_lazy

from .models import Place
from .forms import PlaceForm

class PlaceListView(generic.ListView):
	template_name ="places/list_places.html"
	context_object_name = 'object_list'

	def get_queryset(self):
		return Place.objects.all()

@login_required
def create_place(request):
	if request.method == "POST":
		form = PlaceForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('places:place_list')
		else:
			return render(request, 'places/edit_places.html', {'form':form})
	else:
		form = PlaceForm()
		return render(request, 'places/edit_places.html', {'form':form})


@login_required
def edit_place(request, pk):
	instance = Place.objects.get(id=pk)
	username = "&username=digitalarchiv"
	if request.method == "GET":
		placeName = instance.name
		root = "http://api.geonames.org/searchJSON?q="
		params = "&fuzzy=0.6&lang=de&maxRows=100"
		url = root+placeName+params+username
		try:
			r = requests.get(url)
		except requests.exceptions.RequestException as e:
			url = e
		response = r.text
		responseJSON = json.loads(response)
		responseJSON = responseJSON['geonames']
		form = PlaceForm(instance = instance)
		print(url)
		#form = OrtForm({'geonames_id':123})
		return render(request, 'places/edit_places.html',
			{'object':instance, 'form':form, 'responseJSON':responseJSON}
			)
	else:
		form = PlaceForm(request.POST, instance = instance)
		if form.is_valid():
			form.save()
		return redirect('places:place_list')


class PlaceDelete(DeleteView):
	model = Place
	template_name = 'webpage/confirm_delete.html'
	success_url = reverse_lazy('places:place_list')

places/templates/places/edit_places.html
{% extends "webpage/base.html" %}
{% block Titel %}Edit Places{% endblock %}

{% block scriptHeader %}
{% include 'autocomplete_light/static.html' %}
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

{% if object %}
<div class="row">
	<div class="col-md-4">
{% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{%if object %} Edit {% else %} Create {% endif %}</h3>
            </div>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% crispy form %}
                    {% if object %}
                    <a class="btn btn-default btn-block" target="_blank">Check<span id="currentID"></span></a>
                    {% endif %}
                    <input class="btn btn-primary btn-block" type="submit" value="Save" />
                   <!-- commented delete function out to avoid unforseen consequences. E.g. I deleted Linz. But as Linz is related with OÖ-Landesarchiv, 
                   OÖ-Landesarchiv was deleted and with it all Bände and Einträge related to it-->

                   <!--  {% if object %}
                    <a class ="btn btn-danger btn-sm" href="{% url 'places:place_delete' pk=object.id %}">delete</a>
                    {% endif %} --> 
                </form>
	       </div>
       </div>
{% if object %}       
   </div>
    <div class ="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading">
                <form class="form-group">
                    <select class="form-control" id="geonamesSELECT">
                            {% if object.geonames_id or object.lat %}
                                <option id="geonamesOption" value="{{ object.name }}_{{ object.lat }}_{{ object.lng }}_{{ object.geonames_id }}">DB-Entry | {{ object.name }} | {{ object.lat }} | {{ object.lng }} | {{ object.geonames_id }}</option>
                            {% endif %}
                            {% for dict in responseJSON %}
                            <option id="geonamesOption" value="{{ dict.countryName }}_{{ dict.name }}_{{ dict.lat }}_{{ dict.lng }}_{{ dict.geonameId }}"> {{ dict.countryName }} | {{ dict.name }} | {{ dict.lat }} | {{ dict.lng }} | {{ dict.geonameId }}</option>
                            {% endfor %}
                        </select>
                    </form>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<script type="text/javascript">
    function popupCreateName() {
        var url = "{% url 'labels:label_create' %}";
        var MyWindow = window.open(url,"","width=300, height=500");
    }
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $("#id_alias_name-autocomplete").after('<button id="add_aliasName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus" /></button>');
    });
    $(document).ready(function(){
        $("#id_alternative_name-autocomplete").after('<button id="add_alternativeName" type="button" class="btn btn-sm btn-success" onclick="popupCreateName()"><span class="glyphicon glyphicon-plus"/></button>');
    });
</script>

<script type="text/javascript">
	$( document ).ready(function() {
 		$("#map").remove()
    	$("#parentMap").append("<div id='map'></div>");
    	var placeName = $("#geonamesSELECT option:selected").text();
    	var gps1 = placeName.split(/\|/)[2];
    	var gps2 = placeName.split(/\|/)[3];
    	var map = L.map('map').setView([gps1, gps2], 10);

    	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

    	L.marker([gps1, gps2]).addTo(map)
    	.bindPopup(placeName)
    	.openPopup();
		});
</script>

<script type="text/javascript">
    $( document ).ready(function(){
        var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
        var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

    });
</script>

<script type="text/javascript">
    $("#geonamesSELECT").change(function(){
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");
       var placeName = $("#geonamesSELECT option:selected").text();
        var gps1 = placeName.split(/\|/)[2];
        var gps2 = placeName.split(/\|/)[3];
        var map = L.map('map').setView([gps1, gps2], 15);
        var geonameId = placeName.split(/\|/)[4];
        $('#id_lat').val(parseFloat(gps1));
        $('#id_lng').val(parseFloat(gps2));
        $('#id_geonames_id').val(parseInt(geonameId));
       var gndURL = "http://www.geonames.org/"+geonameId.trim();
        var lookupButton = $("#currentID");
        $(lookupButton).text(gndURL);
        $(lookupButton).parent().attr("href",gndURL);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);
        
        L.marker([gps1, gps2]).addTo(map)
            .bindPopup(placeName)
            .openPopup();
});
</script>
{% endblock %}

places/templates/places/list_places.html
{% extends "webpage/base.html" %}
{% block Titel %}List Places{% endblock %}

{% block scriptHeader %}
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
{% if object_list %}
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default panel-fixed" >
			<div class="panel-heading" style="text-align:center;">
				<h3>Places</h3><a href="{% url 'places:place_create' %}">(add another Place)</a>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Name</th>
							<th>GeoNames</th>
						</tr>
					</thead>
					<tbody>
						{% for object in object_list %}
						<tr>
							<td><a href="{% url 'places:place_edit' pk=object.id %}">{{ object }}</a></td>
							<td>{{ object.geonames_id }}</td>
						</tr>
						{% endfor %}
					</tbody>	
				</table>					
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading" style="text-align:center;">
				<h3>Geovisualisation</h3>
			</div>
			<div class="panel-body">
				<div id="parentMap"></div>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
	$( document ).ready(function() {
 		$("#map").remove()
    	$("#parentMap").append("<div id='map'></div>");
/*    	var placeName = $("#geonamesSELECT option:selected").text();
    	var gps1 = placeName.split(/\|/)[2];
    	var gps2 = placeName.split(/\|/)[3];*/
    	var map = L.map('map').setView([48.69096, 9.14062], 5);

    	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

    	{% for object in object_list %}
    	{% if object.lat %}
    	L.marker([{{ object.lat }}, {{ object.lng }}])
    	.addTo(map)
    	.bindPopup("<h1>{{ object.name }}</h1> <table class='table table-striped'> <tr> <td>Name: </td> <td>{{ object.name }}</td> </tr> </table>");
    	{% endif %}
    	{% endfor %}
		});
</script>
{% endif %}
{% endblock %}