bomber/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'list/$', views.bomber, name='bomber_list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.BomberDetailView.as_view(), name='bomber_detail')
]

browsing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'bombers/$', views.BomberListView.as_view(), name='browse_bombers'),
    url(r'persons/$', views.PersonListView.as_view(), name='browse_persons'),
]

crew/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'list/$', views.person, name='person_list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.PersonDetailView.as_view(), name='person_detail')
]

django_spaghetti/urls.py
from django.conf.urls import url
from django_spaghetti.views import plate

urlpatterns = [
    url(r'^$', plate, name='plate'),
]

flj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from bomber.api_views import BomberViewSet
from places.api_views import PlaceViewSet
from labels.api_views import LabelViewSet
from crew.api_views import PersonViewSet

from autocomplete_light import shortcuts as al
al.autodiscover()


router = routers.DefaultRouter()
router.register(r'bombers', BomberViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'labels', LabelViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'labels/', include('labels.urls', namespace='labels')),
    url(r'bombers/', include('bomber.urls', namespace='bombers')),
    url(r'browsing/', include('browsing.urls', namespace='browsing')),
    url(r'crew/', include('crew.urls', namespace='crew')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
]

webpage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.start_view, name="start"),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^imprint/$', views.imprint, name='imprint'),
    url(r'^about/$', views.about_view, name='about'),
    url(r'^team/$', views.team, name='team'),
]

webpage/forms.py
# -*- coding: utf-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.core.urlresolvers import reverse
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div


class form_user_login(forms.Form):
	username = forms.CharField(label='Username',widget=forms.TextInput)
	password = forms.CharField(label='Password',widget=forms.PasswordInput)

	def __init__(self, *args, **kwargs):
		super(form_user_login, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.add_input(Submit('submit','Login'))

webpage/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout

from .forms import form_user_login


def imprint(request):
    context = RequestContext(request)
    return render(request, 'webpage/imprint.html', context)


def start_view(request):
    context = RequestContext(request)
    return render(request, 'webpage/index.html', context)


def about_view(request):
    context = RequestContext(request)
    return render(request, 'webpage/about.html', context)


def team(request):
    context = RequestContext(request)
    return render(request, 'webpage/team.html', context)


#################################################################
#               views for login/logout                          #
#################################################################

def user_login(request):
    if request.method == 'POST':
        form = form_user_login(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(request.GET.get('next', '/'))
                else:
                    return HttpResponse('not active.')
            else:
                return HttpResponse('user does not exist')
    else:
        form = form_user_login()
        return render(request, 'webpage/user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return render_to_response('webpage/user_logout.html')

webpage/templates/webpage/about.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">
  <h1>Über das Projekt</h1>
  <p>Die Web-Applikation erfasst und visualisiert alle westalliierten Flugzeugabstürze während des Zweiten Weltkrieges im heutigen Österreich. Dabei werden die Schicksale von mehr als 10.000 amerikanischen und britischen Besatzungsmitgliedern nachgezeichnet und dargestellt. Die vernetzte Betrachtungsweise unterschiedlicher Quellen ermöglicht dabei erstmals einen vollständigen Einblick in ein bisher kaum erforschtes Segment des alliierten Bombenkrieges und trägt zur Klärung von Vermisstenschicksalen bei.</p>
  <p>Das Projekt DAACDA umfasst die Sammlung, Auswertung und Darstellung von Daten und Informationen zum Schicksal amerikanischer und britischer Flugzeugbesatzungen, die zwischen 1939 und 1945 über dem heutigen Österreich zum Absturz kamen, in Gefangenschaft gerieten, Opfer von Verbrechen wurden und/oder zu Tode kamen. </p>
  <p>Basis des Projekts ist die Entwicklung einer Web-Applikation, die in Zusammenarbeit zwischen dem <a href="https://geschichte.uni-graz.at/de/">Institut für Geschichte</a> (Fachbereich Zeitgeschichte) der Karl-Franzens-Universität Graz und dem <a href="http://www.oeaw.ac.at/acdh/">Austrian Center for Digital Humanities</a> der Österreichischen Akademie der Wissenschaften von <a href="http://www.oeaw.ac.at/acdh/en/andorfer">Peter Andorfer</a> entwickelt wird. Dabei werden über 10.000 Personen erfasst, Spuren nachvollzogen, Daten gesammelt, untereinander verknüpft und der Öffentlichkeit sowie der wissenschaftlichen Forschung zugänglich gemacht. So wird ein bislang kaum erschlossenes Segment des Bombenkrieges, mit individuellen Schicksalen und Wahrnehmungen verwoben und visualisiert. Das Projekt ist dabei in wissenschaftliche Unternehmungen eingebettet, die sich der Gewalt gegen abgeschossene alliierte Flugzeugbesatzungen („Fliegerlynchjustiz“) aber auch den sogenannten „Missing in Action“-Cases verschrieben haben. Dabei wurde eine vollständige Sammlung von Daten zu allen Flugzeugabstürzen und davon betroffenen Besatzungen vorgenommen, die nun in die Applikation einfließen. So entsteht erstmals ein umfassendes Bild der Schicksale abgeschossener Flieger im heutigen Österreich, das von einer vernetzten Betrachtung von Quellen, Daten und Informationen aus US-, britischen, deutschen und österreichischen Archiven gespeist wird. Die Nachzeichnung von Spuren und deren Visualisierung dient dabei nicht nur ihrer Darstellung, sondern ist – integriert in eine Zusammenarbeit mit dem US Department of Defense – der Klärung der Schicksale jener Flieger gewidmet, die bis zum heutigen Tage als vermisst gelten.</p>
  <h3>Literatur</h3>
  <ul>
    <li><a href="https://www.schoeningh.de/katalog/titel/978-3-506-78137-6.html">Hoffmann, Fliegerlynchjustiz, 2015</a></li>
    <li><a href="http://www.bundesheer.at/download_archiv/pdfs/missing_in_action.pdf">Goll/Hoffmann, Missing in Action, 2016</a></li>
</div>

{% endblock %}

webpage/templates/webpage/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>{% block Titel %} Crashed Bombers and their Crews {% endblock %}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block metaDescription %}
      <meta name="description" content="A Web-App">
      {% endblock %}
      <meta name="author" content="Peter Andorfer">

      <!-- Bootstrap -->
      <link rel="stylesheet" href="{% static 'webpage/libraries/bootstrap335/css/bootstrap.min.css' %}"/></link>
      <!-- jQuery UI -->
      <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css"/>

      <!-- leaflet -->
        <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet/leaflet.css' %}"/></link>
        <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet.markercluster/dist/MarkerCluster.css' %}"/></link>
        <link rel="stylesheet" href="{% static 'webpage/libraries/leaflet.markercluster/dist/MarkerCluster.Default.css' %}"/></link>
        <script src="{% static 'webpage/libraries/leaflet/leaflet.js' %}"></script>
        <script src="{% static 'webpage/libraries/leaflet.markercluster/src/leaflet.markercluster-src.js' %}"></script>
      <!-- leaflet end  -->

      <!--scroll to top CSS -->
        <link rel="stylesheet" href="{% static 'webpage/libraries/scroll-to-top/css/ap-scroll-top.min.css'%}"></link>

      <!-- jQuery -->
        <script type="text/javascript" src="{% static 'webpage/libraries/jquery/jquery.js' %}"></script>

      <!--scroll to top -->
        <script src="{% static 'webpage/libraries/scroll-to-top/js/ap-scroll-top.min.js'%}"></script>

      <!-- Piwik -->
        <script type="text/javascript">
          var _paq = _paq || [];
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
            var u="//clarin.oeaw.ac.at/piwik/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', 24]);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
          })();
        </script>
        <noscript>
          <p><img src="//clarin.oeaw.ac.at/piwik/piwik.php?idsite=24" style="border:0;" alt="" /></p>
        </noscript>
      <!-- End Piwik Code -->

       <!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
        <script type="text/javascript">
            window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":"{% url 'webpage:imprint' %}","theme":"dark-bottom"};
        </script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
        <!-- End Cookie Consent plugin -->

        <style type="text/css">
          html {
          height: 100%;
          }
          body {
          display: flex;
          flex-direction: column;
          height: 100%;
          }
          header {
          flex: 0 0 auto;
          }
          .main-content {
          flex: 1 0 auto;
          }
          footer {
          flex: 0 0 auto;
          background-color: #333; /*#F8F8F8*/
          color: #ffffff;
          font-size: 13px;
          padding: 20px;
         /* position: absolute;*/
          left: 0;
          right: 0;
          width: 100%;
          margin-top: 10px;
          }
        </style>
        {% block scriptHeader %}
        {% endblock %}
  </head>

  <body role="document">
    <header>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation!</span>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
            <span class="icon-bar"/>
          </button>
        </div>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'webpage:start' %}">Start</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:team' %}">Team</a>
                    </li>
                    <li>
                        <a href="{% url 'datamodel:plate' %}">Data Model</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:imprint' %}">Impressum/Imprint</a>
                    </li>
                  </ul>
                </li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Explore Data
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{%url 'bombers:bomber_list' %}">Crashed Aircrafts</a>
                    </li>
                    <li>
                        <a href="{%url 'crew:person_list' %}">The Crews</a>
                    </li>
                    <li>
                        <a href="{% url 'api-root' %}">API</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter and Search
                  <span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{%url 'browsing:browse_bombers' %}">Crashed Aircrafts</a>
                    </li>
                    <li>
                        <a href="{%url 'browsing:browse_persons' %}">The Crews</a>
                    </li>
                  </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <!-- <li>
                  <a href="#">DummyLink</a>
              </li> -->
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">place for LogIn<span class="caret"/>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'webpage:user_login' %}">Log-In</a>
                    </li>
                    <li>
                        <a href="{% url 'webpage:user_logout' %}">Log-Out</a>
                    </li>
                  </ul>
              </li>
            </ul>
        </div>
    </nav>
    </header>
    <section class="main-content">
        <div class="alert alert-warning">
        A <a href="{% url 'webpage:about' %}"><strong>new version</strong></a> of DAACDA is being developed. Work in Progress, but entered data will be preserved.<a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        </div>
        <div id="content" class="container">
            {% block content %}
            {% endblock %}
        </div>
    </section>
    <footer>
    <div class="container">
     <footer>
        <div class="row text-center">
          <div class="col-sm-4">
            <a href="https://acdh.oeaw.ac.at/acdh/" class="navlink" target="_blank">
                <img src="{% static 'webpage/img/ACDH_kurz_Weiss.png' %}" alt="ACDH" width="25%"/>
            </a>
          </div>
          <div class="col-sm-4">
            <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="navlink" target="_blank">
                <img src="{% static 'webpage/img/by-sa.png' %}" alt="CC-BY-SA-4.0" width="25%"/>
            </a>
          </div>
          <div class="col-sm-4">
            <a href="https://github.com/acdh-oeaw/DAACDA" class="navlink" target="_blank">
                <img src="{% static 'webpage/img/GitHub-Mark-Light-64px.png' %}" alt="ACDH" width="10%"/>
            </a>
          </div>
        </div>
        </div>
        </footer>

    {% block scripts %}
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/bootstrap335/js/bootstrap-tab.js' %}"></script>
    <script type="text/javascript" src="{% static 'webpage/libraries/jquery-ui-1.11.4/jquery-ui.min.js' %}"></script>
    <!-- scroll-up-bottom -->
    <script type="text/javascript">
            // Setup plugin with default settings
            $(document).ready(function() {
                $.apScrollTop({
                    'onInit': function(evt) {
                        console.log('apScrollTop: init');
                    }
                });
            });
    </script>
    {% endblock %}
  </body>
</html>

webpage/templates/webpage/confirm_delete.html
{% extends "webpage/base.html" %}
{% block content %}

<!-- Launch modal on page load http://stackoverflow.com/questions/10233550/launch-bootstrap-modal-on-page-load -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title">Confirm delete</h3>
      </div>
      <div class="modal-body">
       	<form action="" method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete the {{ object.get_classname }}:<br /> <strong>{{ object }}</strong> ?</h4>
    		<input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
		</form>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>
</form>
{% endblock content %}
{% block scripts %}
{{block.super}}
<script type="text/javascript">
$(window).load(function(){
        $('#myModal').modal('show');
    });
</script>


{% endblock scripts %}

webpage/templates/webpage/index.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <img src="{% static 'webpage/img/1_NARA_cropped.jpg' %}" alt="First" width="1200" height="600" title="NARA">
            <div class="carousel-caption">
             <!--  <h3>Research data</h3>
              <p>Neolithic and Copper Age in Greece and Anatolia (7000-3000 BC)</p> -->
            </div>
          </div>

          <div class="item">
            <img src="{% static 'webpage/img/3_NARA_cropped.jpg' %}" alt="Second" width="1200" height="600" title="NARA">
            <div class="carousel-caption">
              <!-- <h3>Data model</h3>
              <p>High granularity of the archaeological data structure</p> -->
            </div>
          </div>

          <div class="item">
            <img src="{% static 'webpage/img/2_NARA_cropped.jpg' %}" alt="Third" width="1200" height="600" title="NARA">
            <div class="carousel-caption">
              <!-- <h3>Linked Open Data</h3>
              <p>Open Access and Data reuse</p> -->
            </div>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container text-center">
    <h2 class="bs-docs-featurette-title"><strong>D</strong>owned <strong>A</strong>llied <strong>A</strong>ir <strong>C</strong>rew <strong>D</strong>atabase <strong>A</strong>ustria</h2>
    <h3>DAACDA</h3>
    <div>
        <h4 class="text-center">The application’s purpose is the publication of data about allied air crews whose planes were downed above Austria during World War II. The data running this application was gathered by <strong><a href="https://www.hdgoe.at/ueber-uns/">Georg Hoffmann</a></strong> and <strong><a href="https://www.hdgoe.at/ueber-uns/">Nicole Goll</a></strong>.</h4>
    </div>
    <div class="row" style="padding-top:30px;">
        <div class="col-md-6">
            <a href="{%url 'webpage:about' %}" class="btn btn-info btn-lg">Know more</a>
        </div>
        <div class="col-md-6">
            <a href="{%url 'bombers:bomber_list' %}" class="btn btn-info btn-lg">explore</a>
        </div>
    </div>
</div>

{% endblock %}

webpage/templates/webpage/team.html
{% extends "webpage/base.html" %}
{% load staticfiles %}
{% block content %}

<div class="container">
    <h1>Team</h1>
    <h2><a href="https://www.hdgoe.at/ueber-uns/">Nicole-Melanie Goll</a></h2>
    <p>Mag.<sup>a</sup>  Dr.<sup>in</sup></p>
    <p>Historikerin</p>
    <p>1982 in Graz geboren, Studium der Geschichte an der Karl-Franzens-Universität Graz, 2007–2014 Doktorat an der Andrassy Universität Budapest und der Universität Graz, 2010–2017 wissenschaftliche Mitarbeiterin und Lecturer am Fachbereich Zeitgeschichte des Instituts für Geschichte der Universität Graz, zudem wissenschaftliche Mitarbeit an zahlreichen Forschungsprojekten des Bundesministeriums für Landesverteidigung und Sport (BMLVS) und kuratorische Tätigkeiten, zuletzt 2014 Ausstellung „Die Steiermark und der Große Krieg“ des Universalmuseums Joanneum.</p>
    <p>Seit September 2017 wissenschaftliche Mitarbeiterin am Haus der Geschichte Österreichs im Rahmen des von der Österreichischen Akademie der Wissenschaften und dem Zukunftsfonds der Republik Österreich geförderten Forschungsprojektes „Downed Allied Air Crew Database Austria“.</p>
    <h4>Forschungsschwerpunkte</h4>
    <p>Zeitalter der Weltkriege, mit Schwerpunkt auf Europa (Luftkrieg im 1. und 2. Weltkrieg; NS-Kriegsverbrechen und Nachkriegsjustiz, Heimatfront, Propaganda, Genese und Funktion von Heldenfiguren, Propaganda, Fürsorgepolitik in Österreich-Ungarn)</p>
    <h4>Aktuelle Publikationen</h4>
    <ul>
        <li>(mit Katharina Dick, Georg Hoffmann), Bombenkrieg in Graz, Salzburg 2017</li>
        <li>(mit Harald Heppner, Georg Hoffmann), Globaler Krieg. Visionen und ihre Umsetzung, Wien 2017</li>
        <li><a href="http://www.bundesheer.at/download_archiv/pdfs/missing_in_action.pdf">(mit Georg Hoffmann), Missing in Action – Failed to Return. Ein Gedenkbuch, Wien 2016</a></li>
        <li>(mit Werner Suppanz), Heimatfront Steiermark. Der Erste Weltkrieg auf lokaler/regionaler Ebene. (Klartext Verlag), (erscheint 2018)</li>
    </ul>
    <h2><a href="https://www.hdgoe.at/ueber-uns/">Georg Hoffmann</a></h2>
    <p>Mag. Dr. phil.</p>
    <p>Historiker, Studium der Geschichte an der Karl-Franzens-Universität Graz, Doktoratsstudium an der Karl-Franzens-Universität Graz sowie der Andrassy Universität Budapest, von 2009–2017 wissenschaftlicher Mitarbeiter bzw. Lecturer am Institut für Geschichte der Universität Graz (Fachbereich Zeitgeschichte), 2013 Research Fellow am Center Austria der University of New Orleans, Mitarbeit an zahlreichen Forschungsprojekten des Bundesministeriums für Landesverteidigung und Sport (BMLVS) sowie kuratorische Tätigkeiten, zuletzt 2015/2016 Ausstellung „41 Tage. Kriegsende 1945 – Verdichtung der Gewalt“ (Akademie der Wissenschaften/BMLVS/Universität Graz). Seit April 2017 Kurator am Haus der Geschichte Österreich.</p>
    <h4>Forschungsschwerpunkte</h4>
    <p>Sozial- und Kulturgeschichte von Gewalt und Krieg (besonders im Luftkrieg), Nationalsozialismus, TäterInnenforschung, Österreichische Geschichte</p>
    <h4>Aktuelle Publikationen</h4>
    <ul>
        <li>Hoffmann, Georg: »Vergeltung« im Bombenkrieg. Lynchjustiz an alliierten Flugzeugbesatzungen in Deutschland, Österreich und Ungarn 1943-1945, in: Oliver von Wrochem (Hg.): Repressalien und Terror. “Vergeltungsaktionen“ im deutsch besetzten Europa 1939–1945, Paderborn 2017, S. 249-265</li>
        <li>(mit Katharina Dick, Nicole-Melanie Goll), Bombenkrieg in Graz, Salzburg 2017</li>
        <li>(mit Harald Heppner, Nicole-Melanie Goll), Globaler Krieg. Visionen und ihre Umsetzung, Wien 2017</li>
        <li><a href="http://www.bundesheer.at/download_archiv/pdfs/missing_in_action.pdf">(mit Nicole-Melanie Goll), Missing in Action – Failed to Return. Ein Gedenkbuch, Wien 2016</a></li>
        <li>“Fliegerlynchjustiz”. Gewalt gegen abgeschossene alliierte Flugzeugbesatzungen 1943-1945 (Krieg in der Geschichte Bd. 88), Paderborn 2015.</li>
    </ul>
    <h2><a href="https://www.oeaw.ac.at/acdh/team/current-team/martin-kirnbauer/">Martin Kirnbauer</a></h2>
    <p>BA</p>
    <p>Bis 2012 Fachhochschulstudium Informationsberufe in Eisenstadt, seit 2015 Masterstudium Geschichte mit Schwerpunkt Zeitgeschichte an der Universität Wien. Ab 2011 im Medienbereich und einem juristischen Fachverlag tätig, elektronisches Publizieren. Seit 2017 am Austrian Centre for Digital Humanities (ACDH) der Österreichischen Akademie der Wissenschaften, Wien.</p>
    <h2><a href="https://www.oeaw.ac.at/acdh/team/current-team/peter-andorfer/">Peter Andorfer</a></h2>
    <p>Mag. Dr. phil.</p>
    <p>Studium der Geschichte und Germanistik an der Universität Innsbruck; wissenschaftlicher Mitarbeiter an der Herzog-August-Bibliothek Wolfenbüttel im Projekt DARIAH-DE. Seit 2015 wissenschaftlicher Mitarbeiter am Austrian Centre for Digital Humanities (ACDH) der Österreichischen Akademie der Wissenschaften.</p>
</div>

{% endblock %}

webpage/templates/webpage/user_login.html
{% extends "webpage/base.html" %}

{% block content %}

<div class="container"></br>
{% if form.errors %}

<p style="color: red;">Please correct the error{{ form.errors|pluralize }} below.</p>

{% endif %}

{% load crispy_forms_tags %}

{% crispy form form.helper %}

</div>
{% endblock %}

webpage/templates/webpage/user_logout.html
{% extends "webpage/base.html" %}

{% block Titel %}logout{% endblock %}

{% block content %}

<div class="jumbotron container">
    
    <h1>Sayōnara!</h1>
    
    <p>You've signed out</p>

</div>

{% endblock content %}