bomber/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'list/$', views.bomber, name='bomber_list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.BomberDetailView.as_view(), name='bomber_detail')
]

crew/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'list/$', views.person, name='person_list'),
    url(r'^detail/(?P<pk>[0-9]+)$', views.PersonDetailView.as_view(), name='person_detail')
]

flj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from bomber.api_views import BomberViewSet
from places.api_views import PlaceViewSet
from labels.api_views import LabelViewSet
from crew.api_views import PersonViewSet

from autocomplete_light import shortcuts as al
al.autodiscover()


router = routers.DefaultRouter()
router.register(r'bombers', BomberViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'places', PlaceViewSet)
router.register(r'labels', LabelViewSet)


urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webpage.urls', namespace='webpage')),
    url(r'places/', include('places.urls', namespace='places')),
    url(r'labels/', include('labels.urls', namespace='labels')),
    url(r'bombers/', include('bomber.urls', namespace='bombers')),
    url(r'browsing/', include('browsing.urls', namespace='browsing')),
    url(r'crew/', include('crew.urls', namespace='crew')),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^datamodel/', include('django_spaghetti.urls', namespace='datamodel')),
]

places/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^list/$', views.PlaceListView.as_view(), name='place_list'),
url(r'^create/$', views.create_place, name='place_create'),
url(r'^edit/(?P<pk>[0-9]+)$', views.edit_place, name='place_edit'),
url(r'^delete/(?P<pk>[0-9]+)$', views.PlaceDelete.as_view(), name='place_delete')
]

bomber/models.py
from django.db import models
from places.models import Place


class Bomber(models.Model):
    macr_nr = models.CharField(max_length=50, blank=True, verbose_name="MARC-Nr")
    air_force = models.CharField(max_length=50, blank=True, verbose_name="Air Force")
    plane_type = models.CharField(max_length=50, blank=True, verbose_name="Type of the aircraft")
    plane_id = models.CharField(max_length=50, blank=True, verbose_name="The aircraft´s ID")
    name = models.CharField(max_length=250, blank=True, verbose_name="Name of the aircraft")
    bomber_group = models.CharField(max_length=50, blank=True, verbose_name="Bomber Group")
    squadron = models.CharField(max_length=75, blank=True)
    date_of_crash = models.DateField(blank=True, null=True)
    reason_of_crash = models.CharField(max_length=250, blank=True)
    target_place = models.ForeignKey(Place, blank=True, null=True, related_name="targetPlace")
    last_seen = models.ForeignKey(Place, blank=True, null=True, related_name="lastSeen")
    crash_place = models.ForeignKey(Place, blank=True, null=True, related_name="crashPlace")
    lat = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    lng = models.DecimalField(max_digits=20, decimal_places=12, blank=True, null=True)
    comment = models.TextField(blank=True)

    def __str__(self):
        return "{}".format(self.macr_nr)

bomber/views.py
from django.shortcuts import render
from django_tables2 import RequestConfig
from django.views.generic.detail import DetailView
from django.db.models import Count

from crew.models import Person
from .models import Bomber
from .tables import BomberTable


def bomber(request):
    table = BomberTable(Bomber.objects.all())
    RequestConfig(request).configure(table)
    object_list = Bomber.objects.all()
    return render(request, 'bomber/list_bomber.html', {'table': table, 'object_list': object_list})


class BomberDetailView(DetailView):
    model = Bomber

    def get_context_data(self, **kwargs):
        context = super(BomberDetailView, self).get_context_data(**kwargs)
        current_object = self.object
        context['destiny'] = Person.objects.filter(bomber=current_object.id).values('destiny_checked').annotate(total=Count('destiny_checked')).order_by('destiny_checked')
        context['crew_list'] = Person.objects.filter(bomber=current_object.id).order_by('destiny_checked')
        return context

bomber/templates/bomber/bomber_detail.html
{% extends "webpage/base.html" %}
{% block Titel %}Bomber Details{% endblock %}

{% block scriptHeader %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading"> 
        <h2>{{ object.plane_type }}<small> {{ object.air_force }} | {{ object.squadron }} | {{ object.bomber_group }} | {{ object.plane_id }} </small></h2>
    </div>
    <div class="panel panel-body">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Aircraft</h3>
                    </div>
                    <div class="panel panel-body">
                        <table class="table table-hover table-condensed">
                            <tr>
                                <th class="col-md-3">MACR-Nr</th>
                                <td class="col-md-9">{{ object.macr_nr }}</td>
                            </tr>
                            <tr>
                                <th>Plane´s Name</th>
                                <td>{{ object.name|default:"<small>no name provided</small>" }}</td>
                            </tr>
                            <tr>
                                <th>Unit</th>
                                <td>{{ object.air_force }} | {{ object.squadron }} | {{ object.bomber_group }} | {{ object.plane_id }}</td>
                            </tr>
                            <tr>
                                <th>Crash-Date</th>
                                <td>{{ object.date_of_crash }}</td>
                            </tr>
                            <tr>
                                <th>Attack Place</th>
                                <td><a href="{% url 'places:place_edit' pk=object.target_place.id %}">{{ object.target_place }}</a></td>
                            </tr>
                            <tr>
                                <th>last seen (place)</th>
                                <td><a href="{% url 'places:place_edit' pk=object.last_seen.id %}">{{ object.last_seen }}</a></td>
                            </tr>
                            <tr>
                                <th>last seen (coordinates)</th>
                                <td>{{ object.lat }}, {{ object.lng }}</td>
                            </tr>
                            <tr>
                                <th>Crahs Place</th>
                                <td><a href="{% url 'places:place_edit' pk=object.crash_place.id %}">{{ object.crash_place }}</a></td>
                            </tr>
                            <tr>
                                <th>Reason of the crash</th>
                                <td>{{ object.reason_of_crash }}</a></td>
                            </tr>
                            <tr>
                                <th>Note</th>
                                <td>{{ object.comment }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Crew</h3>
                    </div>
                    <div class="panel panel-body">
                        <table class="table table-boarderd table-hover table-condensed">
                            <tr>
                                <th>Name</th>
                                <th>Destiny</th>
                            </tr>
                            {% for x in crew_list %}
                            <tr>
                                <td><a href="{% url 'crew:person_detail' pk=x.id %}">{{ x.last_name }}, {{ x.first_name }}</a> <small>{{ x.rank }}</small></td>
                                <td>{{ x.destiny_checked }}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>

            <div class="cold-md-6">
                <div id="map"></div>
                <hr/>
                <div id="donut" style="height: 400px"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
    $('#donut').highcharts({
        chart: {
            width: 500,
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45
            }
        },
        title: {
            text: 'Destiny of the Crew Members'
        },
        plotOptions: {
            pie: {
                innerSize: 50,
                depth: 40
            }
        },
        series: [{
            name: 'Crew Memebers',
            data: [
            {% for x in destiny %}["{{x.destiny_checked}}", {{x.total}}],{% endfor %}
            ]
        }]
    });
});
</script>
<script type="text/javascript">

    $( document ).ready(function() {
        var crash_gps1 = parseFloat("{{ object.crash_place.lat }}")
        var crash_gps2 = parseFloat("{{ object.crash_place.lng }}")
        $("#parentMap").append("<div id='map'></div>");
        var map = L.map('map').setView([crash_gps1, crash_gps2], 8);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        L.marker([crash_gps1, crash_gps2]).addTo(map)
        .bindPopup('Crash Place:  <a href="{% url 'places:place_edit' pk=object.crash_place.id %}">{{ object.crash_place }}</a>');

    {% if object.last_seen.name %}
        var deathGps1 = parseFloat("{{ object.last_seen.lat }}")
        var deathGps2 = parseFloat("{{ object.last_seen.lng }}")
        L.marker([deathGps1, deathGps2]).addTo(map)
        .bindPopup('Place last seen: <a href="{% url 'places:place_edit' pk=object.last_seen.id %}">{{ object.last_seen }}</a>');
    {% endif %}

    {% if object.target_place.name %}
        var deathGps1 = parseFloat("{{ object.target_place.lat }}")
        var deathGps2 = parseFloat("{{ object.target_place.lng }}")
        L.marker([deathGps1, deathGps2]).addTo(map)
        .bindPopup('Attack place: <a href="{% url 'places:place_edit' pk=object.target_place.id %}">{{ object.target_place }}</a>');
    {% endif %}
        });

</script>


{% endblock %}

bomber/templates/bomber/list_bomber.html
{% extends "webpage/base.html" %}
{% block Titel %}List Crashed Bombers{% endblock %}

{% block scriptHeader %}
    {% load render_table from django_tables2 %}
        <style>
            #map { height: 500px; }
        </style>
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading" style="text-align:center;">
                <h3>Crashed Bombers</h3>
            </div>
            <div class="panel-body">    
                {% render_table table %}
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default panel-fixed" >
            <div class="panel-heading" style="text-align:center;">
                <h3>All Crash Sites</h3>
            </div>
            <div class="panel-body">
                <div id="parentMap"></div>
            </div>    
        </div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {
        $("#map").remove()
        $("#parentMap").append("<div id='map'></div>");

        var map = L.map('map').setView([48.69096, 9.14062], 5);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.light',
        accessToken: 'pk.eyJ1IjoiY3NhZTgwOTIiLCJhIjoiY2lnM2FoZWpjMDJqZnY1a2gxdWl6a29kaiJ9.FQXlsKIu60WhiXLrfI59VA'
        }).addTo(map);

        {% for object in object_list %}
        {% if object.crash_place.lat %}
        L.marker([{{ object.crash_place.lat }}, {{ object.crash_place.lng }}])
        .addTo(map)
        .bindPopup("<h3><a href='{% url "bombers:bomber_detail" pk=object.id %}'>{{ object.macr_nr }}</a></h3> <table class='table table-striped'> <tr> <td>Crashplace: </td> <td>{{ object.crash_place }}</td> </tr> </table>");
        {% endif %}
        {% endfor %}
        });
</script>
{% endblock %}